export const endpoints = {
  login: "/auth/login",
  register: "/auth/register",
  sendOtp: "/auth/register/send-otp",
  verifyOtp: "/auth/register/verify-otp",
  getProducts: "/products",
  getProductById: "/products/{id}",
  createProduct: "/products",
  updateProduct: "/products/{id}",
  deleteProduct: "/products/{id}",
  getCategories: "/categories",
  getCategoryById: "/categories/{id}",
  createCategory: "/categories",
  updateCategory: "/categories/{id}",
  deleteCategory: "/categories/{id}",
  getUsers: "/users",
  getUserById: "/users/{id}",
  createUser: "/users",
  updateUser: "/users/{id}",
  deleteUser: "/users/{id}",
};
